name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: us-east-2
        mask-password: 'true'

    - name: Build, tage, and push image to Amazon ECR
      run: |
        docker build -t wwebsite .
        docker tag wwebsite:latest AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/wwebsite:latest
        docker push AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/wwebsite:latest
      env:
        AWS_REGION: us-east-2
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        
      
 
